#install.packages('tm')
#install.packages('twitteR')
#install.packages('wordcloud')
#install.packages('RColorBrewer')
#install.packages('e1017')
#install.packages('class')

library(twitteR)
library(tm)
library(wordcloud)
library(RColorBrewer)
